baseURL = "https://blogdevops.github.io/"
contentDir = "content/posts"
languageCode = "en-us"
title = "Minha carreira DevOps"

[permalinks]
posts = "/:year/:month/:slug/"

[[menu.main]]
identifier = "home"
name = "Home"
url = "/"

[[menu.main]]
identifier = "posts"
name = "Posts"
url = "/posts/"
theme = "holy"
