baseURL = "https://blogdevops.github.io/"
contentDir = "content"
languageCode = "en-us"
title = "Minha carreira DevOps"
theme = "holy"

[params]
  author = "Artur barreto"

[[menu.main]]
  identifier = "home"
  name = "Home"
  url = "/"

[[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about"

[[menu.main]]
  identifier = "posts"
  name = "Posts"
  url = "/posts/"

[permalinks]
  posts = "/posts/:year/:month/:day/:slug/"
